# Generated by Django 4.2 on 2023-04-22 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_passportinfo_passport_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passportinfo',
            name='passport_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='passport issue date'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='passport_issue_place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='passport issue place'),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='passport_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(100000)], verbose_name='passport number'),
        ),
    ]
