# Generated by Django 4.2 on 2023-04-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_passportinfo_passport_issue_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporatecustomertype',
            name='creation_date',
            field=models.DateField(blank=True, null=True, verbose_name='company creation date'),
        ),
    ]
