# Generated by Django 4.2 on 2023-05-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_corporatecustomertype_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='state',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Declined'), (3, 'Accepted'), (4, 'Finished')], default=1),
        ),
    ]
